export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface LayoutProps {
  children: React.ReactNode;
  notifications: React.ReactNode;
  users: React.ReactNode;
  revenue: React.ReactNode;
}

export default function RootLayout({
  children,

  users,
  revenue,
}: LayoutProps) {
  return (
    <div>
      <h1 className="bg-green-500">ths is archived layout </h1>
      {children}
    </div>
  );
}
