"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/login" className="text-green-700">
          {" "}
          login
        </Link>
        <Link href="/register" className="text-green-700">
          {" "}
          register
        </Link>
        <Link href="/forgot-password" className="text-green-700">
          {" "}
          forgot password
        </Link>
        <h1 className="bg-red-500 h-24">this is navbar</h1>
        {children}

        <h1 className="bg-green-500 h-24">this is footer</h1>
      </body>
    </html>
  );
}
