import Notifications from "./@notificatons/page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,

  users,
  revenue,
  notificatons,
}: {
  children: React.ReactNode;
  notifications: React.ReactNode;
  users: React.ReactNode;
  revenue: React.ReactNode;
}) {
  return (
    <div>
      {revenue}
      {children}
      {notificatons}
    </div>
  );
}
